### ISSUE TITLE
tests failed only on copr builds

### ISSUE THREAD

**Issue by brancomat** [ARPA-SIMC/dballe-web#16]
The same sources (v0.3-1) build fine on moncic-ci:
https://simc.arpae.it/moncic-ci/dballe-web/202305181130/master/fedora36/build.log
but some tests fail only on copr:
https://download.copr.fedorainfracloud.org/results/simc/stable/fedora-36-x86_64/05931641-dballe-web/builder-live.log.gz

Relevant logs:
```
running build_ext
test_client (tests.test_web_api.TestBasic) ... ok
test_export (tests.test_web_api.TestBasic) ... FAIL
test_get_data (tests.test_web_api.TestBasic) ... FAIL
test_init (tests.test_web_api.TestBasic) ... FAIL
test_set_filter (tests.test_web_api.TestBasic) ... FAIL
test_client (tests.test_web_api.TestEmpty) ... ok
test_export (tests.test_web_api.TestEmpty) ... FAIL
test_get_data (tests.test_web_api.TestEmpty) ... FAIL
test_client (tests.test_web_api.TestInit) ... ok
test_not_initialized (tests.test_web_api.TestInit) ... FAIL

======================================================================
FAIL: test_export (tests.test_web_api.TestBasic)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/dballe-web-0.3-1/tests/test_web_api.py", line 212, in test_export
    self.assertEqual(res.headers["Content-Type"], "application/octet-stream")
AssertionError: 'text/html; charset=utf-8' != 'application/octet-stream'
- text/html; charset=utf-8
+ application/octet-stream


======================================================================
FAIL: test_get_data (tests.test_web_api.TestBasic)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/dballe-web-0.3-1/tests/test_web_api.py", line 160, in test_get_data
    self.assertEqual(res.get_json(), {
AssertionError: None != {'time': 100, 'rows': [{'i': 1, 'r': 'syn[591 chars] 0}]}

======================================================================
FAIL: test_init (tests.test_web_api.TestBasic)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/dballe-web-0.3-1/tests/test_web_api.py", line 117, in test_init
    self.assertEqual(res.get_json(), {
AssertionError: None != {'time': 100, 'explorer': {'data_limit': [760 chars]0'}}}

======================================================================
FAIL: test_set_filter (tests.test_web_api.TestBasic)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/dballe-web-0.3-1/tests/test_web_api.py", line 233, in test_set_filter
    self.assertEqual(res.get_json(), {
AssertionError: None != {'time': 100, 'explorer': {'data_limit': [861 chars]0'}}}

======================================================================
FAIL: test_export (tests.test_web_api.TestEmpty)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/dballe-web-0.3-1/tests/test_web_api.py", line 46, in test_export
    self.assertEqual(res.get_data(), b"")
AssertionError: b'<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3[198 chars]p>\n' != b''

======================================================================
FAIL: test_get_data (tests.test_web_api.TestEmpty)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/dballe-web-0.3-1/tests/test_web_api.py", line 41, in test_get_data
    self.assertEqual(res.get_json(), {"time": 100, "rows": []})
AssertionError: None != {'time': 100, 'rows': []}

======================================================================
FAIL: test_not_initialized (tests.test_web_api.TestInit)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/dballe-web-0.3-1/tests/test_web_api.py", line 54, in test_not_initialized
    self.assertEqual(res.get_json(), {
AssertionError: None != {'time': 100, 'explorer': {'data_limit': [423 chars] 0}}}

----------------------------------------------------------------------
Ran 10 tests in 0.098s

FAILED (failures=7)
Test failed: <unittest.runner.TextTestResult run=10 errors=0 failures=7>
error: Test failed: <unittest.runner.TextTestResult run=10 errors=0 failures=7>
```

**Comment by spanezz** [comment]
I tried to compare the two logs, and the dependencies seem exactly the same: the only thing I noticed is that on moncic-ci I can see deprecationwarnings, while on copr I do not, which hints at some difference in how the tests are run, but it does not hint at anything that should make tests fail. Tricky...

**Comment by brancomat** [comment]
stale issue
